### ISSUE TITLE
Feature request: support for blended electrodes

### ISSUE THREAD

**Issue by ejfdickinson** [FaradayInstitution/BPX#23]
Provide support in the BPX standard for electrodes to contain a specified blend of different materials (e.g. by weight or atom fraction) with discretely defined OCP functions and maximum concentrations.

[request from industrial contributor]

**Comment by tinosulzer** [comment]
Everything currently in the "Electrode" class (as opposed to "Contact") applies to the material only. So a blended electrode would replace
```python
negative_electrode: Electrode = Field(
        alias="Negative electrode",
    )
```
with a list of the materials that make up the electrode

**Comment by rtimms** [comment]
done in #33
