### ISSUE TITLE
PDF of the BPX standard – binary file included in Git repository

### ISSUE THREAD

**Issue by agriyakhetarpal** [FaradayInstitution/BPX#74]
The recent [`v0.4.1` release](https://github.com/FaradayInstitution/BPX/releases/tag/v0.4.1) via https://github.com/FaradayInstitution/BPX/commit/e94f0a24075f255db59193f950c84df46cfed879 has introduced a PDF file in the Git history – a change that has the potential to cause (and causes) a few problems:

- since Git stores the complete history of the file, this is bound to make the repository unnecessarily big when the git trees are updated on subsequent commits
- poor diffs, since there are no diffs for PDFs, at least with version control systems like Git

I'd advise:
- revising the history (`git filter-branch` should be able to do this) to remove that commit completely, and re-create the releases on GitHub/PyPI as necessary
- either, switching to the inclusion of the PDF by uploading it as a release artifact for the v0.4.1 release (similar to the approach followed by https://github.com/pybamm-team/pybamm-data/releases/tag/v1.0.0 – not that there are binary files there, though) that users can download separately
- or, if the PDF must be included in the source tree, Git LFS is a better option.
- alternatively, if there is a Markdown or LaTeX edition of the standard that can be compiled into a PDF with some instructions for those who want to do it, switch to that

Since this change was performed very recently in the commit history at the time of writing, I'd advise going forward with a combination of 1), and then opting for either 2) or 3) or 4).

cc: @rtimms

**Comment by agriyakhetarpal** [comment]
I've checked and the size of the PDF is 196 KiB, which, while not much in comparison to what a 1 MP image could be, is still worth removing rather than having to do it later because of the compounding effect of VCS history, plus it sets a good precedent for repository hygiene.

**Comment by rtimms** [comment]
Thanks, is this something you could assist with?

**Comment by agriyakhetarpal** [comment]
Sure! I can assist with this, but I think you would be able to handle it better because I have "write" permissions on this repository and not "maintain" permissions, so I can't force-push to the main branch. Since we don't have the v0.4.1 release on PyPI yet (https://pypi.org/project/bpx/#history), we just need to re-create the GitHub release with modified commit history (and then we can upload the PDF to the release).

The PyPI release was skipped in this workflow run: https://github.com/FaradayInstitution/BPX/actions/runs/12117521598/job/33780127640 because the workflow file is improperly configured; the upload is triggered by a manual input and not the GitHub release. Also, we should now switch to trusted publishing instead of using the API key. This would require administrator permissions for both GitHub and PyPI.

**Comment by rtimms** [comment]
Fixed. New release [here](https://github.com/FaradayInstitution/BPX/releases/tag/v0.4.1). Thanks for raising this!
